# KartaBattlePass Configuration

# General BattlePass settings
battlepass:
  max-level: 100
  # Formula: base-exp * level
  # Example for level 10: 100 * 10 = 1000 XP needed
  exp-per-level-base: 100

# XP Sources
# Define how much XP is given for certain actions.
xp-sources:
  # XP for killing mobs
  mob-kills:
    ZOMBIE: 5
    SKELETON: 5
    CREEPER: 8
    SPIDER: 4
    ENDERMAN: 10
    WITCH: 12
    PIGLIN: 3
    PIGLIN_BRUTE: 15
  # XP for mining blocks
  mining:
    COAL_ORE: 1
    IRON_ORE: 2
    GOLD_ORE: 3
    DIAMOND_ORE: 10
    ANCIENT_DEBRIS: 25
  # XP for fishing
  fishing: 5
  # XP for crafting
  crafting:
    DIAMOND_SWORD: 50
    DIAMOND_PICKAXE: 50

# Rewards format
# rewards:
#   <level>:
#     free:
#       - "command one"
#       - "command two"
#     premium:
#       - "premium command one"
#       - "premium command two"
#
# NEW: Reward settings
rewards:
  auto-grant: false # Set to true to automatically claim rewards on level up.

# Example rewards - These are now moved to rewards.yml
# rewards:
#   1:
#     free:
#       - "minecraft:give %player% minecraft:iron_sword 1"
#       - "minecraft:give %player% minecraft:bread 16"
#     premium:
#       - "minecraft:give %player% minecraft:diamond_sword{Enchantments:[{id:sharpness,lvl:1}]} 1"
#       - "minecraft:give %player% minecraft:golden_apple 2"
#   5:
#     free:
#       - "minecraft:give %player% minecraft:iron_ingot 10"
#     premium:
#       - "minecraft:give %player% minecraft:diamond 5"
#       - "eco give %player% 250"
#   10:
#     free:
#       - "eco give %player% 100"
#     premium:
#       - "eco give %player% 500"
#       - "minecraft:give %player% minecraft:experience_bottle 32"
#   25:
#     free:
#       - "minecraft:give %player% minecraft:ender_pearl 8"
#     premium:
#       - "lp user %player% parent set vip"
#       - "say &e%player% &6telah mencapai &lLevel 25 &6dan mendapatkan rank &b&lVIP&r&6!"
#   50:
#     free:
#       - "minecraft:give %player% minecraft:netherite_ingot 1"
#     premium:
#       - "minecraft:give %player% minecraft:netherite_ingot 4"
#       - "minecraft:give %player% minecraft:totem_of_undying 1"
#       - "say &e%player% &6telah mencapai &lLevel 50 &6dan menjadi legenda server!"
