name: KartaBattlePass
version: '1.2.0-SNAPSHOT'
main: com.minekarta.kartabattlepass.KartaBattlePass
api-version: '1.21'
authors: [MinekartaStudio]
description: A BattlePass plugin.
depend:
  - PlaceholderAPI
softdepend:
  - Vault
  - Citizens
  - FancyNPC
commands:
  kbattlepass:
    description: Main command for KartaBattlePass.
    usage: /<command>
    aliases: [kbp, battlepass, bp]
permissions:
  kbattlepass.admin:
    description: Grants access to all admin commands.
    default: op
  kbattlepass.open:
    description: Permission to open the Battle Pass GUI.
    default: true
  kbattlepass.claim:
    description: Permission to claim rewards.
    default: true
  kbattlepass.progress.others:
    description: Permission to view other players' progress.
    default: op
  kartabattlepass.premium:
    description: Grants access to the premium reward track.
    default: op
