name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run checks
        run: ./gradlew check

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KartaBattlePass-JAR
          path: kartabattlepass-bukkit/build/libs/*.jar
